import type { Book, Review, User } from '../types'

// ─── Books ────────────────────────────────────────────────────────────────────

export const MOCK_BOOKS: Book[] = [
  {
    id: 'book-1',
    title: 'O Nome do Vento',
    author: 'Patrick Rothfuss',
    coverGradient: 'from-[#c8a96e] to-[#e8635a]',
    genres: ['Fantasy'],
    tropes: ['Chosen One', 'Magic Academy', 'Slow Burn'],
    pageCount: 662,
    publishedYear: 2007,
    seriesName: 'A Crônica do Matador do Rei',
    seriesNumber: 1,
    rating: 4.8,
    ratingsCount: 12400,
    synopsis:
      'Meu nome é Kvothe. Ouvi pessoas me chamarem de Edema Ruh, de estudante, de ladrão...',
    emotionsBreakdown: [
      { emotion: 'love', percentage: 72, count: 8928 },
      { emotion: 'surprised', percentage: 18, count: 2232 },
      { emotion: 'cried', percentage: 10, count: 1240 },
    ],
  },
  {
    id: 'book-2',
    title: 'Neuromancer',
    author: 'William Gibson',
    coverGradient: 'from-[#6a9fcf] to-[#b87cde]',
    genres: ['Sci-Fi'],
    tropes: ['Dystopia', 'Hacker', 'Artificial Intelligence'],
    pageCount: 271,
    publishedYear: 1984,
    rating: 4.3,
    ratingsCount: 8700,
    synopsis: 'O céu sobre o porto tinha a cor da televisão sintonizada num canal morto...',
    emotionsBreakdown: [
      { emotion: 'surprised', percentage: 55, count: 4785 },
      { emotion: 'love', percentage: 30, count: 2610 },
      { emotion: 'irritated', percentage: 15, count: 1305 },
    ],
  },
  {
    id: 'book-3',
    title: 'A Casa no Cerrado',
    author: 'Carla Madeira',
    coverGradient: 'from-[#7c9e7a] to-[#c8a96e]',
    genres: ['Literary'],
    tropes: ['Family Drama', 'Coming of Age'],
    pageCount: 304,
    publishedYear: 2021,
    rating: 4.6,
    ratingsCount: 5200,
    synopsis: 'Uma história sobre maternidade, perda e recomeço no cerrado brasileiro...',
    emotionsBreakdown: [
      { emotion: 'cried', percentage: 68, count: 3536 },
      { emotion: 'love', percentage: 22, count: 1144 },
      { emotion: 'surprised', percentage: 10, count: 520 },
    ],
  },
  {
    id: 'book-4',
    title: 'O Problema dos Três Corpos',
    author: 'Liu Cixin',
    coverGradient: 'from-[#6a9fcf] to-[#0a0807]',
    genres: ['Sci-Fi'],
    tropes: ['First Contact', 'Hard Sci-Fi', 'Conspiracy'],
    pageCount: 399,
    publishedYear: 2008,
    rating: 4.5,
    ratingsCount: 18000,
    synopsis: 'Durante a Revolução Cultural Chinesa, uma transmissão secreta chega ao espaço...',
  },
  {
    id: 'book-5',
    title: 'Tudo é Rio',
    author: 'Carla Madeira',
    coverGradient: 'from-[#e8635a] to-[#c8a96e]',
    genres: ['Literary', 'Romance'],
    tropes: ['Forbidden Love', 'Tragedy'],
    pageCount: 200,
    publishedYear: 2015,
    rating: 4.7,
    ratingsCount: 9800,
    synopsis: 'Uma paixão que devasta, que faz sangrar, que faz lembrar e que não acaba...',
  },
  {
    id: 'book-6',
    title: 'It — A Coisa',
    author: 'Stephen King',
    coverGradient: 'from-[#1a1210] to-[#e8635a]',
    genres: ['Horror', 'Thriller'],
    tropes: ['Coming of Age', 'Found Family', 'Supernatural'],
    pageCount: 1104,
    publishedYear: 1986,
    rating: 4.4,
    ratingsCount: 22000,
    synopsis: 'Derry, Maine. Uma cidade onde as crianças desaparecem e os adultos não percebem...',
  },
]

// ─── Users ────────────────────────────────────────────────────────────────────

export const MOCK_CURRENT_USER: User = {
  id: 'user-current',
  name: 'Sofia Mendes',
  username: '@sofiamendes',
  avatar: '👩🏻',
  bio: 'Leitora compulsiva de fantasia e ficção literária. Tomo café às 2am com um livro na mão.',
  aesthetic: 'dark-academia',
  followersCount: 341,
  followingCount: 128,
  booksReadCount: 87,
  reviewsCount: 34,
  readingStreak: 12,
  averageRating: 4.1,
  favoriteGenres: ['Fantasy', 'Literary', 'Horror'],
  badges: [
    { id: 'b1', label: 'Maratonista', emoji: '🏃', unlockedAt: '2025-01-15' },
    { id: 'b2', label: 'Explorador', emoji: '🧭', unlockedAt: '2025-03-02' },
    { id: 'b3', label: 'Crítico', emoji: '✍️', unlockedAt: '2025-04-10' },
    { id: 'b4', label: 'Social', emoji: '👥', unlockedAt: '2025-04-18' },
  ],
}

export const MOCK_USERS: User[] = [
  {
    id: 'user-1',
    name: 'Ana Silva',
    username: '@anasilva',
    avatar: '👩🏻',
    aesthetic: 'dark-academia',
    followersCount: 892,
    followingCount: 210,
    booksReadCount: 142,
    reviewsCount: 67,
    readingStreak: 30,
    averageRating: 4.3,
    favoriteGenres: ['Fantasy', 'Literary'],
    badges: [],
  },
  {
    id: 'user-2',
    name: 'Pedro Costa',
    username: '@pedrocosta',
    avatar: '👨🏽',
    aesthetic: 'minimalist',
    followersCount: 456,
    followingCount: 89,
    booksReadCount: 58,
    reviewsCount: 21,
    readingStreak: 5,
    averageRating: 3.9,
    favoriteGenres: ['Sci-Fi', 'Thriller'],
    badges: [],
  },
  {
    id: 'user-3',
    name: 'Mariana Luz',
    username: '@marianaluz',
    avatar: '👩🏾',
    aesthetic: 'cottagecore',
    followersCount: 1240,
    followingCount: 304,
    booksReadCount: 203,
    reviewsCount: 98,
    readingStreak: 62,
    averageRating: 4.6,
    favoriteGenres: ['Literary', 'Romance'],
    badges: [],
  },
]

// ─── Reviews ──────────────────────────────────────────────────────────────────

export const MOCK_REVIEWS: Review[] = [
  {
    id: 'review-1',
    userId: 'user-1',
    user: { id: 'user-1', name: 'Ana Silva', username: '@anasilva', avatar: '👩🏻', aesthetic: 'dark-academia' },
    bookId: 'book-1',
    book: { id: 'book-1', title: 'O Nome do Vento', author: 'Patrick Rothfuss', coverGradient: 'from-[#c8a96e] to-[#e8635a]' },
    rating: 5,
    emotions: ['love', 'surprised'],
    text: 'Simplesmente perfeito. A prosa de Rothfuss é poesia pura. Kvothe é um dos protagonistas mais complexos que já encontrei na fantasia moderna.',
    likesCount: 127,
    commentsCount: 23,
    isLiked: false,
    createdAt: new Date(Date.now() - 2 * 3600_000).toISOString(),
  },
  {
    id: 'review-2',
    userId: 'user-2',
    user: { id: 'user-2', name: 'Pedro Costa', username: '@pedrocosta', avatar: '👨🏽', aesthetic: 'minimalist' },
    bookId: 'book-2',
    book: { id: 'book-2', title: 'Neuromancer', author: 'William Gibson', coverGradient: 'from-[#6a9fcf] to-[#b87cde]' },
    rating: 4,
    emotions: ['surprised'],
    text: 'Cyberpunk na sua forma mais crua. Gibson antecipou muito do nosso futuro digital. Denso, mas recompensador.',
    likesCount: 89,
    commentsCount: 15,
    isLiked: true,
    createdAt: new Date(Date.now() - 5 * 3600_000).toISOString(),
  },
  {
    id: 'review-3',
    userId: 'user-3',
    user: { id: 'user-3', name: 'Mariana Luz', username: '@marianaluz', avatar: '👩🏾', aesthetic: 'cottagecore' },
    bookId: 'book-3',
    book: { id: 'book-3', title: 'A Casa no Cerrado', author: 'Carla Madeira', coverGradient: 'from-[#7c9e7a] to-[#c8a96e]' },
    rating: 5,
    emotions: ['cried', 'love'],
    text: 'Este livro me destroçou de formas que não imaginava. A narrativa sobre maternidade, perda e recomeço é absolutamente visceral.',
    likesCount: 203,
    commentsCount: 41,
    isLiked: false,
    createdAt: new Date(Date.now() - 24 * 3600_000).toISOString(),
  },
]

// ─── Quote of the day ─────────────────────────────────────────────────────────

export const QUOTES_OF_THE_DAY = [
  { text: 'Não há amigo tão leal quanto um livro.', author: 'Ernest Hemingway' },
  { text: 'A leitura é para a mente o que o exercício é para o corpo.', author: 'Joseph Addison' },
  { text: 'Um leitor vive mil vidas antes de morrer.', author: 'George R.R. Martin' },
  { text: 'Os livros são espelhos: só vemos neles o que já temos dentro de nós.', author: 'Carlos Ruiz Zafón' },
]
